- Type: Training
  Trainers:
    - Name: Abraham Aranguren
      Email: admin@7asecurity.com
      Image: trainer-abraham-aranguren.png
      Twitter: 7asecurity
      Biography: "After 13 years in itsec and 20 in IT Abraham is now the CEO of 7ASecurity (7asecurity.com), 
        a company specializing in penetration testing of web/mobile apps, infrastructure, code reviews 
        and training. Former senior penetration tester / team lead at Cure53 (cure53.de) and Version 1 
        (www.version1.com). Creator of “Practical Web Defense” - a hands-on eLearnSecurity attack / 
        defense course (www.elearnsecurity.com/PWD), OWASP OWTF project leader, an OWASP flagship 
        project (owtf.org), Major degree and Diploma in Computer Science, some certs: CISSP, OSCP, GWEB, 
        OSWP, CPTS, CEH, MCSE:Security, MCSA:Security, Security+. As a shell scripting fan trained by 
        unix dinosaurs, Abraham wears a proud manly beard. He writes on Twitter as @7asecurity 
        @7a_ @owtfp or https://7asecurity.com/blog. Multiple presentations, pentest reports and 
        recordings can be found at https://7asecurity.com/publications"
  Title: "Hacking Modern Desktop apps: Master the Future of Attack Vectors"
  URL: /register/?id=sku_
  SectionId: sku_
  Description: "This course is a 100% hands-on deep dive into the OWASP Security Testing Guide and
    relevant items of the OWASP Application Security Verification Standard (ASVS), so this
    course covers and goes beyond the OWASP Top Ten.<br>
    Long are the days since web servers were run by perl scripts and desktop apps written
    in Delphi. What is common between Microsoft Teams, Skype, Bitwarden, Slack and
    Discord? All of them are written in Electron: JavaScript on the client.
    Modern Desktop apps share traditional attack vectors and also introduce new
    opportunities to threat actors. This course will teach you how to review modern desktop
    apps, showcasing Node.js and Electron but using techniques that will also work against
    any other desktop app platform. Ideal for Penetration Testers, Desktop app Developers
    as well as everybody interested in JavaScript/Node.js/Electron app security.<br>
    All action, no fluff, improve your security analysis workflow and immediately apply these
    gained skills in your workplace, packed with exercises, extra mile challenges and CTF,
    self-paced and suitable for all skill levels, with continued education via unlimited email
    support and lifetime access to training portal with step-by-step video recordings and
    interesting apps to practice, including all future updates for free."
- Type: Training
  Trainers:
    - Name: John DiLeo
      Email: john.dileo@owasp.org
      Image: trainer-john-dileo.jpg
      Twitter: gr4ybeard
      Biography: "Dr. John DiLeo is the Auckland-area leader of the OWASP New Zealand Chapter. In his recent 
        roles, he has been responsible for managing enterprises software assurance programs, with emphasis on 
        governance, secure development practices, and security training.<br>
        Before specializing in application security, John was active as a Java enterprise architect and Web 
        application developer. In an earlier life, John had specialized in developing discrete-event simulations 
        of large distributed systems, in a variety of languages - including the Java-based language (FreeSML) he 
        developed as part of his doctoral research.<br>
        John is on the core team for the OWASP Software Assurance Maturity Model (SAMM) Project, and is Co-Leader 
        of the OWASP Application Security Curriculum Project."
  Title: "Threat Modeling: Getting from None to Done"
  URL: /register/?id=sku_
  SectionId: sku_
  Description: "This session offers participants an interactive introduction to Threat Modeling, based on the 
    instructor's learning and experience over the past several years. A primary focus of this course is the 
    introduction of threat modeling activities into your organization's software development processes, to 
    improve the overall quality and security of the applications you build.<br>
    As a recent 'convert' to the application security world, your instructor has developed his 'expertise' 
    in threat modeling by gathering information from a variety of sources. He's combined those learnings with his 
    own experience to create a practical threat modeing approach he has successfully applied within his 
    professional roles.<br>
    In addition to addressing key questions around the 'Five Ws', the presentation will cover the 
    'Four Questions' approach to developing a model, and include several interactive exercises to provide direct 
    experience. A brief review of available modeing tools will also be included, along with a discussion of the 
    opportunities and challenges for introducing Threat Modelng into your SDLC."